services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=BTCS Coach
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - MAIL_MAILER=log
      - SESSION_DRIVER=file
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    volumes:
      - app_storage:/var/www/html/storage
      - app_database:/var/www/html/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_storage:
    driver: local
  app_database:
    driver: local