[variables]
PHP_VERSION = "8.3"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y sqlite3"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

# Skip build phase entirely - use committed assets
[phases.build]

[start]
cmd = "mkdir -p database && touch database/database.sqlite && php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan route:clear && php artisan migrate --force && php artisan db:seed --class=ProductionDataSeeder --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"