[build]
builder = "nixpacks"

[deploy]
startCommand = "touch /app/database/database.sqlite && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 600
healthcheckInterval = 30
healthcheckInitialDelaySeconds = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10