[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php artisan db:seed --class=ProductionDataSeeder --force && php artisan admin:check && php artisan serve --host=0.0.0.0 --port=$PORT"